// Specimen gallery: runs the real share renderer (src/share/*) against a Mona Lisa tree.
// The "edits" are drawn here in canvas rather than generated by a model — see NOTE below —
// but every plate is produced by the same code the app ships.

import { FORMATS, GROUPS, defaultsFor, buildTree, REQUIREMENTS, render, toBlob, setWordmark } from '../src/share/index.js';
import { encodeMp4, encodeGif, canEncodeVideo } from '../src/share/video.js';
import { layout } from '../src/layout.js';

const ROMAN = 'I II III IV V VI VII VIII IX X XI XII XIII XIV XV XVI XVII XVIII XIX XX XXI XXII'.split(' ');
const el = (tag, cls, txt) => { const e = document.createElement(tag); if (cls) e.className = cls; if (txt != null) e.textContent = txt; return e; };
const KEEP = 'hdl.keep.v1';
const marks = (() => { try { return JSON.parse(localStorage.getItem(KEEP)) || {}; } catch { return {}; } })();
const saveMarks = () => { try { localStorage.setItem(KEEP, JSON.stringify(marks)); } catch { /* private window */ } };

// ─────────────────────────────────────────── stand-in "edits", drawn not generated
async function paint(src, fn, filter) {
  const c = new OffscreenCanvas(src.width, src.height);
  const x = c.getContext('2d');
  if (filter) x.filter = filter;
  x.drawImage(src, 0, 0);
  x.filter = 'none';
  fn?.(x, src.width, src.height);
  return c.convertToBlob({ type: 'image/jpeg', quality: 0.88 });
}

// Duchamp did this by hand in 1919 too, so a hand-drawn stand-in is in period.
function mustache(x, W, H) {
  const cx = W * 0.457, cy = H * 0.2925, w = W * 0.062, h = H * 0.0125;
  x.fillStyle = 'rgba(28,20,12,.93)';
  for (const s of [1, -1]) {
    x.save(); x.translate(cx, cy); x.scale(s, 1);
    x.beginPath();
    x.moveTo(0, -h * 0.15);
    x.bezierCurveTo(w * 0.45, -h * 0.55, w * 0.85, -h * 1.5, w * 1.18, -h * 2.5);
    x.bezierCurveTo(w * 1.02, -h * 0.9, w * 0.7, h * 0.15, w * 0.28, h * 0.8);
    x.bezierCurveTo(w * 0.16, h * 0.95, w * 0.06, h * 0.8, 0, h * 0.5);
    x.closePath(); x.fill();
    x.restore();
  }
  x.beginPath();
  x.ellipse(W * 0.4575, H * 0.3345, W * 0.021, H * 0.0155, 0, 0, Math.PI * 2);
  x.fill();
}

function aviators(x, W, H) {
  const eyes = [[0.4045, 0.2265], [0.5105, 0.2215]];
  const rx = W * 0.049, ry = H * 0.0245;
  x.strokeStyle = 'rgba(20,20,24,.95)';
  x.lineWidth = W * 0.008;
  x.beginPath();
  x.moveTo(W * eyes[0][0] + rx * 0.85, H * eyes[0][1] - ry * 0.3);
  x.quadraticCurveTo(W * 0.4575, H * 0.213, W * eyes[1][0] - rx * 0.85, H * eyes[1][1] - ry * 0.3);
  x.stroke();
  for (const [ex, ey] of eyes) {
    const gx = W * ex, gy = H * ey;
    const g = x.createLinearGradient(gx - rx, gy - ry, gx + rx, gy + ry);
    g.addColorStop(0, 'rgba(24,26,32,.93)'); g.addColorStop(0.55, 'rgba(48,54,66,.9)'); g.addColorStop(1, 'rgba(14,15,19,.95)');
    x.beginPath();
    x.ellipse(gx, gy + ry * 0.25, rx, ry * 1.25, 0, 0, Math.PI * 2);
    x.fillStyle = g; x.fill();
    x.strokeStyle = 'rgba(15,15,18,.95)'; x.lineWidth = W * 0.006; x.stroke();
    x.beginPath();
    x.ellipse(gx - rx * 0.35, gy - ry * 0.25, rx * 0.3, ry * 0.22, -0.5, 0, Math.PI * 2);
    x.fillStyle = 'rgba(255,255,255,.22)'; x.fill();
  }
  x.strokeStyle = 'rgba(20,20,24,.9)'; x.lineWidth = W * 0.009;
  x.beginPath(); x.moveTo(W * 0.356, H * 0.2275); x.lineTo(W * 0.333, H * 0.2345); x.stroke();
  x.beginPath(); x.moveTo(W * 0.559, H * 0.2225); x.lineTo(W * 0.583, H * 0.2305); x.stroke();
}

async function buildImages(srcBlob) {
  const src = await createImageBitmap(srcBlob);
  const w = src.width, h = src.height; // read before close(): a closed bitmap reports 0
  const out = {
    seed: srcBlob,
    mustache: await paint(src, mustache),
    shades: await paint(src, aviators, 'contrast(1.12) brightness(.92) saturate(.9)'),
    pixar: await paint(src, null, 'saturate(2.1) contrast(1.3) brightness(1.12) hue-rotate(-6deg)'),
    cover: await paint(src, null, 'saturate(1.5) contrast(1.18) brightness(1.06)'),
    passport: await paint(await createImageBitmap(await paint(src, mustache)), null, 'grayscale(1) contrast(1.2) brightness(1.12)'),
    noir: await paint(await createImageBitmap(await paint(src, aviators)), null, 'grayscale(1) contrast(1.45) brightness(.82)'),
  };
  src.close();
  return { images: out, w, h };
}

const TREE = [
  ['seed', null, '', 'Mona Lisa', 0, false],
  ['mustache', 'seed', 'Give me a mustache and a little goatee, like Duchamp did', null, 0.039, true],
  ['shades', 'seed', 'Aviator sunglasses and a leather jacket', null, 0.039, false],
  ['pixar', 'seed', 'Turn me into a Pixar character', null, 0.041, false],
  ['cover', 'seed', 'Put me on the cover of Vogue, headline included', null, 0.043, false],
  ['passport', 'mustache', 'Now make it a passport photo, neutral background', null, 0.038, false],
  ['noir', 'shades', 'Film noir lighting, hard shadow across the face', null, 0.040, true],
];

async function makeTree(srcBlob) {
  const { images, w, h } = await buildImages(srcBlob);
  const ids = Object.fromEntries(TREE.map(([k]) => [k, crypto.randomUUID()]));
  const nodes = TREE.map(([k, parent, prompt, name, cost, star]) => ({
    id: ids[k], type: 'photo', position: { x: 0, y: 0 },
    data: {
      id: ids[k], prompt, name, cost, star, status: 'ready', parents: parent ? [ids[parent]] : [],
      blob: images[k], w, h, seed: 1000 + Math.floor(Math.random() * 9000), url: URL.createObjectURL(images[k]),
    },
  }));
  return buildTree(layout(nodes), { focusId: ids.mustache, model: 'google/gemini-3.1-flash-image' });
}

// ─────────────────────────────────────────── plates
function optionControl(o, opts, onChange) {
  const wrap = el('label', 'opt');
  wrap.append(el('span', null, o.label));
  let input;
  if (o.type === 'bool') { input = el('input'); input.type = 'checkbox'; input.checked = !!opts[o.id]; input.onchange = () => onChange(o.id, input.checked); }
  else if (o.type === 'string') { input = el('input'); input.type = 'text'; input.value = opts[o.id] ?? ''; input.placeholder = String(o.def || ''); input.oninput = () => onChange(o.id, input.value); }
  else {
    input = el('select');
    for (const c of o.choices) { const op = el('option', null, String(c)); op.value = c; input.append(op); }
    input.value = opts[o.id];
    input.onchange = () => onChange(o.id, typeof o.def === 'number' ? Number(input.value) : input.value);
  }
  input.id = `opt-${Math.random().toString(36).slice(2, 9)}`;
  wrap.append(input);
  return wrap;
}

function plate(fmt, i, tree, ctx) {
  const opts = { ...defaultsFor(fmt) };
  const art = el('article', 'plate');
  art.dataset.id = fmt.id;

  const head = el('header', 'pl-head');
  head.append(el('span', 'pl-no', `Plate ${ROMAN[i]}`), el('h2', null, fmt.name), el('p', 'pl-cap', fmt.blurb));
  const mount = el('div', 'mount');
  const foot = el('footer', 'pl-foot');
  const meta = el('span', 'pl-meta');
  const optBox = el('div', 'pl-opts');
  const acts = el('div', 'pl-act');
  foot.append(meta, optBox, acts);
  art.append(head, mount, foot);

  let stop = null;
  const draw = () => {
    if (stop) { stop(); stop = null; }
    mount.replaceChildren();
    const why = REQUIREMENTS[fmt.needs]?.(tree);
    if (why) { mount.append(el('p', 'pl-none', why)); meta.textContent = 'unavailable'; return; }
    setWordmark(ctx.wordmark);

    if (fmt.kind === 'file') {
      const box = el('div', 'filebox');
      if (fmt.id === 'recipe') {
        box.append(el('h3', null, `${opts.name || 'My recipe'}.howdoilook`));
        box.append(el('p', null, 'The whole file, listed. No images, no faces, about 400 bytes.'));
        const ol = el('ol');
        for (const n of tree.edits) ol.append(el('li', null, n.data.prompt));
        box.append(ol);
        box.append(el('p', 'fine', 'Drop it on the canvas, pick any photo, and these run against that face instead.'));
      } else {
        box.append(el('h3', null, `${opts.title || 'howdoIlook'}.html`));
        box.append(el('p', null, `${tree.nodes.length} images inlined as data URIs, laid out exactly as on the canvas, with a slider on every edit to wipe back to its parent.`));
        box.append(el('p', null, 'No network, no server, no dependencies — it opens by double-click and keeps working offline forever.'));
        box.append(el('p', 'fine', 'Save it below to open the real thing.'));
      }
      mount.append(box);
      meta.textContent = 'file';
      return;
    }

    const cv = el('canvas');
    mount.append(cv);
    const src = fmt.kind === 'still' ? fmt.build(tree, opts) : fmt.spec(tree, opts);
    meta.textContent = fmt.kind === 'still'
      ? `${src.w} × ${src.h} px · still`
      : `${src.w} × ${src.h} px · ${src.duration.toFixed(1)}s · silent`;
    const box = mount.getBoundingClientRect();
    const s = Math.min((box.width - 28) / src.w, (box.height - 28) / src.h);
    cv.style.width = `${Math.round(src.w * s)}px`;
    cv.style.height = `${Math.round(src.h * s)}px`;
    const dpr = Math.min(2, window.devicePixelRatio || 1);
    if (fmt.kind === 'still') { render(src, s * dpr, cv); return; }

    art.classList.add('is-motion');
    if (matchMedia('(prefers-reduced-motion: reduce)').matches) {
      render({ w: src.w, h: src.h, bg: src.bg, ops: src.frame(src.duration * 0.72) }, s * dpr, cv);
      meta.textContent += ' · paused (reduced motion)';
      return;
    }
    let raf, t0 = performance.now(), running = true;
    const loop = (now) => {
      if (!running) return;
      render({ w: src.w, h: src.h, bg: src.bg, ops: src.frame(((now - t0) / 1000) % src.duration) }, s * dpr, cv);
      raf = requestAnimationFrame(loop);
    };
    const io = new IntersectionObserver(([e]) => {
      if (e.isIntersecting && !raf) { running = true; t0 = performance.now(); raf = requestAnimationFrame(loop); }
      else if (!e.isIntersecting && raf) { running = false; cancelAnimationFrame(raf); raf = 0; }
    }, { rootMargin: '150px' });
    io.observe(art);
    stop = () => { running = false; cancelAnimationFrame(raf); io.disconnect(); };
  };

  for (const o of fmt.options || []) optBox.append(optionControl(o, opts, (k, v) => { opts[k] = v; draw(); }));

  const save = el('button', 'act save', '⬇ Save');
  save.onclick = () => ctx.save(fmt, tree, opts, save);
  const keep = el('button', 'act keep', 'Keep');
  const cut = el('button', 'act cut', 'Cut');
  const paint2 = () => {
    keep.classList.toggle('on', marks[fmt.id] === 'keep');
    cut.classList.toggle('on', marks[fmt.id] === 'cut');
    art.classList.toggle('cut', marks[fmt.id] === 'cut');
  };
  keep.onclick = () => { marks[fmt.id] = marks[fmt.id] === 'keep' ? undefined : 'keep'; saveMarks(); paint2(); ctx.tally(); };
  cut.onclick = () => { marks[fmt.id] = marks[fmt.id] === 'cut' ? undefined : 'cut'; saveMarks(); paint2(); ctx.tally(); };
  paint2();
  acts.append(save, keep, cut);

  ctx.redraws.push(draw);
  requestAnimationFrame(draw);
  return art;
}

// ─────────────────────────────────────────── boot
export async function start(root, dataUri) {
  const status = root.querySelector('#status');
  const grid = root.querySelector('#grid');
  const tallyEl = root.querySelector('#tally');
  const copyBtn = root.querySelector('#copycut');
  const markBox = root.querySelector('#wordmark');

  // Running from a file:// or localhost build, a plain anchor is the download path.
  const anchorSave = ({ filename, data }) => {
    const a = document.createElement('a');
    a.href = URL.createObjectURL(data instanceof Blob ? data : new Blob([data]));
    a.download = filename;
    a.click();
    setTimeout(() => URL.revokeObjectURL(a.href), 20_000);
    return { status: 'saved' };
  };
  let downloads = { save: anchorSave };
  try {
    const cap = await window.claude?.use?.('downloads');
    if (cap) downloads = cap;
  } catch { /* keep the anchor */ }

  const tree = await makeTree(await (await fetch(dataUri)).blob());
  status.textContent = `${tree.nodes.length} images · ${tree.edits.length} edits · $${tree.totalCost.toFixed(3)}`;

  const ctx = {
    redraws: [],
    wordmark: true,
    tally() {
      const cuts = FORMATS.filter((f) => marks[f.id] === 'cut');
      const keeps = FORMATS.filter((f) => marks[f.id] === 'keep');
      tallyEl.textContent = keeps.length || cuts.length
        ? `${keeps.length} kept · ${cuts.length} cut · ${FORMATS.length - keeps.length - cuts.length} undecided`
        : `${FORMATS.length} formats, none marked yet`;
      copyBtn.disabled = !cuts.length && !keeps.length;
    },
    async save(fmt, t, opts, btn) {
      const label = btn.textContent;
      const done = (s) => { btn.textContent = s; setTimeout(() => { btn.textContent = label; btn.disabled = false; }, 2200); };
      btn.disabled = true;
      try {
        setWordmark(ctx.wordmark);
        let blob, name;
        if (fmt.kind === 'still') {
          btn.textContent = 'Rendering…';
          blob = await toBlob(render(fmt.build(t, opts), 2), 'image/png');
          name = `howdoilook-${fmt.id}.png`;
        } else if (fmt.kind === 'motion') {
          const spec = fmt.spec(t, opts);
          const mp4 = canEncodeVideo();
          blob = mp4
            ? await encodeMp4(spec, { onProgress: (p) => { btn.textContent = `MP4 ${Math.round(p * 100)}%`; } })
            : await encodeGif(spec, { onProgress: (p) => { btn.textContent = `GIF ${Math.round(p * 100)}%`; } });
          name = `howdoilook-${fmt.id}.${mp4 ? 'mp4' : 'gif'}`;
        } else {
          btn.textContent = 'Building…';
          const out = await fmt.make(t, opts);
          blob = out.blob;
          name = out.name;
        }
        await downloads.save({ filename: name, data: blob });
        done('Saved ✓');
      } catch (e) {
        done(e?.code === 'declined' ? 'Cancelled' : 'Failed');
        if (e?.code !== 'declined') console.error(e);
      }
    },
  };

  markBox.checked = true;
  markBox.onchange = () => { ctx.wordmark = markBox.checked; ctx.redraws.forEach((f) => f()); };

  for (const g of GROUPS) {
    const sec = el('section', 'group');
    sec.append(el('h2', 'group-h', g));
    const inner = el('div', 'group-grid');
    for (const f of FORMATS.filter((x) => x.group === g)) inner.append(plate(f, FORMATS.indexOf(f), tree, ctx));
    sec.append(inner);
    grid.append(sec);
  }

  copyBtn.onclick = () => {
    const list = (k) => FORMATS.filter((f) => marks[f.id] === k).map((f) => f.id).join(', ') || 'none';
    navigator.clipboard.writeText(`keep: ${list('keep')}\ncut: ${list('cut')}`);
    copyBtn.textContent = 'Copied ✓';
    setTimeout(() => { copyBtn.textContent = 'Copy my keep / cut list'; }, 2000);
  };
  ctx.tally();

  let t;
  addEventListener('resize', () => { clearTimeout(t); t = setTimeout(() => ctx.redraws.forEach((f) => f()), 200); });
}
